### ISSUE TITLE
System error 577?

### ISSUE THREAD

**Issue by trickster0** [xinbailu/TiEtwAgent#2]
Hello, 

I have been trying to make this work. I am successfully installing the service but when I do net start TiEtwAgent
I am getting the issue in the below screenshot

![image](https://user-images.githubusercontent.com/20028117/184492615-cefa3944-38b6-4228-8f2e-c0107b048954.png)

This is Windows 10 pro 19044.1237, obvsiouly in testsigning mode.

**Comment by xuanxuan0** [comment]
@trickster0 please run the below and provide the output
`Get-AuthenticodeSignature c:\path\to\TiEtwAgent.exe`

Also - how did you generate and sign the executable?

**Comment by trickster0** [comment]
SignerCertificate                         Status                                 Path
-----------------                         ------                                 ----
8707B6B21F8129249F5BB200AFE2DF5E18C500E0  UnknownError                           TiEtwAgent.exe


I did it like it mentions here in the setup section https://github.com/pathtofile/PPLRunner

**Comment by trickster0** [comment]
Hey , false alarm I messed up some files works perfectly. loving your research man!
